### ISSUE TITLE
Add a config option for reference column

### ISSUE THREAD

**Issue by Gtskk** [Zizaco/entrust#240]
Maybe a config option for reference column ? When change the table name, the reference column should be changed. So?

**Comment by pedzed** [comment]
> When change the table name, the reference column should be changed.

No? Not necessarily at least. Can you elaborate your question?

**Comment by Gtskk** [comment]
If I changed roles and members table name, the "hasMany" or "belongsToMany" reference column name will be different.

**Comment by pedzed** [comment]
> If I changed roles and members table name, the "hasMany" or "belongsToMany" reference column name will be different.

I had no problems when I tried it. Can you try to reproduce the problem?

**Comment by Gtskk** [comment]
I'm sorry. I have figured it out.
Thanks.

**Comment by karmendra** [comment]
If my user table is called admin and column on is called admin_id instead of id then the hard coded column reference values in EntrustUserTrait function roles() that defines the relationship has a hardcoded value user_id, and roles_id. How do I refer my column name admin_id here. I did override the function in my Class, but can we have these in the Config file like entrust.role?
