### ISSUE TITLE
Extend, best way?

### ISSUE THREAD

**Issue by iWedmak** [Zizaco/entrust#315]
Not native speaker )
i have a site with multi domain-name system, roles are individual for every domain.
for example:
admin from domain1 cant edit anything in domain2, and otherwise.
admin in domain1 is author in domain2
admin from domain2 is regular user in domain1

what the best way to do such thing?

as i understand in role table must be domain_id 
and on permission check i must support this one as well (or its must be in user instance from beginning) 
i have a table
user_domain (many to many)
and in session i have active domain_id

thanks in advance )

**Comment by rafaelbeckel** [comment]
I'm facing a similar problem here. 

I have an 'apps' table, where a user can be 'developer', 'tester', 'analyst', 'user'; 
a 'conferences' table, where user can be 'admin', 'host', 'speaker', 'subscriber'; 
a 'sites' table where they can be 'admin', 'editor', 'author'... etc.

A user can be the 'developer' of an app and a 'user' in another; and the same for conferences, sites and other namespaces.

I have used Entrust in the past, with great success, but without that complexity.

I've came up with three possible solutions:

___
1) For each namespace (apps, conferences, sites, domains, etc) add a second pivot table, for example:
DOMAIN_USER TABLE:
id
app_id
user_id

DOMAIN_ROLE_USER TABLE:
domain_user_id
role_id

And config Entrust to change the role_user table on-the-fly. A Config::set('entrust.role_user_table', 'domain_role_user') should do it, so it would use your table instead of its standard table. It would use the specific ID of your user-domain relation, instead of the actual user id, but it should filter the roles correctly.

___
2) I don't like this approach, but you could just fake role namespace, like this:
ROLES TABLE:
app_<<APPID>>_developer
app_<<APPID>>_tester
app_<<APPID>>_user
event_<<EVTID>>_owner
event_<<EVTID>>_speaker
event_<<EVTID>>_analyst
event_<<EVTID>>_subscriber
event_<<EVTID>>_customer
site_<<SITEID>>_owner
site_<<SITEID>>_author
site_<<SITEID>>_subscriber
site_<<SITEID>>_customer

Or, in your case:
domain_1_admin
domain_1_user
domain_2_admin
domain_2_user

And then add/delete roles on this table everytime we have a new/deleted app, site or event (or domain); creating a transaction for it to add necessary permissions. You also have to sync and manage updates/deletes.

If you just have domains, it would be a reasonable solution and you don't need to create new table or hook the Config for every request.

___
3) You could extend Entrust to support groups and filtering. I don't really know if I like this option, because simplicity is what made me decide to use it in the first place: it's intuitive and simple to config, learn and use. Adding more tables and options could add some bloat, but this solution would be welcome if it's simple and elegant.
