### ISSUE TITLE
Redirect if hasn't permission to access root.

### ISSUE THREAD

**Issue by Sebbba** [Zizaco/entrust#591]
After reading your docs, there was one question.
If I' specified that user hasn't permission to access some route (in routes.php) - what will happen next?
how can I set up redirects for this case?
how can I set up different redirect for each route?

**Comment by ECarpenter** [comment]
If you are using the middleware to filter routes take a look at the handle functions in the middleware EntrustRole.php and EntrustPermission.php files. The handle functions in these files contain what happens when it fails a check. You should be able replace 

`abort(403);`

with a redirect like

`redirect()->guest('login');`

Just rembeber to run 

`composer dump-autoload` 

after you make the changes.

**Comment by Sebbba** [comment]
Thanks.
I'll check.
