### ISSUE TITLE
hasRole() with multiple roles

### ISSUE THREAD

**Issue by nesl247** [Zizaco/entrust#99]
Please make it so that hasRole() can check an array of roles. Or make it so that ability() doesn't require a permissions array/value to be passed.

Rather than:

``` php
if(Entrust::hasRole('Owner') || Entrust::hasRole('Admin') || Entrust:hasRole('X'))
```

it would be nice to do

``` php
if(Entrust::hasRole(array('Owner', 'Admin', 'X'))
```

**Comment by AbhilashDesign** [comment]
@Albofish Its throwing cachedpermission error. Will it work hasRole(['admin','user'])

**Comment by Albofish** [comment]
@AbhilashDesign The solution I posted is for a 3 year old version of the package. I now use the built in gates / policies so no idea if that is even how you use this now.

**Comment by Ghaji** [comment]
i am also using Entrust and one thing i tend to understand is anytime you add a new Role or Permission you have to go to your view or blade to add the Role or Permission instead why not have a method the will loop through or check if you have any of the Roles or Permissions then do anything you want Rather than adding an if Condition anytime a New Role or Permission is Added
